WebApplication2/WebApplication2/Controllers/ImageWebViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ImageWebViewController : Controller
    {
        ImageWebModel model;

        public ImageWebViewController()
        {
            model = ImageWebModel.GetModel();
        }

        [HttpGet]
        public ActionResult ImageWebView()
        {
            return View();
        }

        [HttpGet]
        public JObject GetServiceData()
        {
            JObject data = new JObject();
            data["status"] = this.model.GetServiceStatus();
            data["imageNum"] = this.model.PhotosNumber;
            return data;
        }

        [HttpGet]
        public JObject GetStudentsData()
        {
            JObject data = new JObject();
            JObject stu1 = new JObject();
            JObject stu2 = new JObject();
            JArray arr = new JArray();
            stu1["id"] = this.model.GetStudentData("student1", "id");
            stu1["firstName"] = this.model.GetStudentData("student1", "firstName");
            stu1["lastName"] = this.model.GetStudentData("student1", "lastName");
            stu2["id"] = this.model.GetStudentData("student2", "id");
            stu2["firstName"] = this.model.GetStudentData("student2", "firstName");
            stu2["lastName"] = this.model.GetStudentData("student2", "lastName");
            arr.Add(stu1);
            arr.Add(stu2);
            data["students"] = arr;
            return data;
        }
    }
}

WebApplication2/WebApplication2/Controllers/LogsViewController.cs
using Infrustructure;
using Newtonsoft.Json.Linq;
using ServiceGuiComunication;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
namespace WebApplication2.Controllers
{
    public class LogsViewController: Controller
    {
        ImageWebModel model;

        public LogsViewController()
        {
            model = ImageWebModel.GetModel();
        }

        [HttpGet]
        public ActionResult LogsView()
        {
            return View();
        }

        [HttpGet]
        public JArray getLogs()
        {
            JArray array = new JArray();
            List < LogData > logsData = this.model.logs;
            if (logsData == null)
            {
                return null;
            }
            List<string[]> logs = new List<string[]>();

            foreach(LogData logData in logsData)
            {
                JObject data = new JObject();
                data["type"] = ((MessageTypeEnum)logData.Type).ToString();
                data["message"] = logData.Message;
                array.Add(data);
            }
            return array;
        }
    }
}

WebApplication2/WebApplication2/Controllers/PhotosViewController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
namespace WebApplication2.Controllers
{
    public class PhotosViewController: Controller
    {
        ImageWebModel model;

        public PhotosViewController()
        {
            model = ImageWebModel.GetModel();
        }

        public ActionResult PhotosView()
        {
            return View();
        }

        [HttpGet]
        public JArray GetPhotosData()
        {
            JArray data = new JArray();
            string path = this.model.OutputDir;
            if (!Directory.Exists(path))
            {
                return null;
            }
            string[] dates = Directory.GetDirectories(path);
            for(int i = 0; i < dates.Length; i++)
            {
                string year = Path.GetFileName(dates[i]);
                string[] months = Directory.GetDirectories(dates[i]);
                for (int z = 0; z < months.Length; z++)
                {
                    JObject d = new JObject();
                    string month = Path.GetFileName(months[z]);
                    d["date"] = year + "/" + month;
                    JArray photos = new JArray();
                    string[] photosUrl = Directory.GetFiles(months[z]);
                    for (int j = 0; j < photosUrl.Length; j++)
                    {
                        photos.Add(photosUrl[j]);
                    }
                    d["photos"] = photos;
                    data.Add(d);
                }
               
            }
            return data;
        }
    }
}

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</head>
<body>

    
    <div class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("ImageWeb", "ImageWebView", "ImageWebView", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Config", "ConfigView", "ConfigView", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Photos", "PhotosView", "PhotosView", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Logs", "LogsView", "LogsView", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>





    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
</html>